<?php

return [
    'Scripts' => [
        ['Name' => 'GREENPEACE UPGRADE',
            'Commentaire' => 'Appels sortants',
            'Version' => 1,
            'ControllerDirectory' => 'GP_Upgrade',
            'ControllerStart' => 'index',
            'Activities' => ['746c19aceb26444192a2a181828ea102'],
        ],
        ['Name' => 'GREENPEACE UPGRADE V2',
            'Commentaire' => 'Appels sortants v2',
            'Version' => 2,
            'ControllerDirectory' => 'GP_Upgrade',
            'ControllerStart' => 'index',
            'Activities' => ['f03aca45b54241259a62041b676fdb8a'],
        ],
        ['Name' => 'UNADEV FIDELISATION',
            'Commentaire' => 'Appels sortants - INACTIFS v1',
            'Version' => 1,
            'ControllerDirectory' => 'UNA_Fid',
            'ControllerStart' => 'index',
            'Activities' => ['e64d913cf18742a383a943b9e609810f'],
        ],
        ['Name' => 'UNADEV FIDELISATION',
            'Commentaire' => 'Appels sortants NOUVEAUX 1ER SEM P20 v1',
            'Version' => 1,
            'ControllerDirectory' => 'UNA_Fid',
            'ControllerStart' => 'index',
            'Activities' => ['4b7c2c39a1be4f5ba2c6d32ca068e3a9', '85e59850b5554d848f3154a99cc7b69a'],
        ],
        ['Name' => 'UNADEV FACTEURS',
            'Commentaire' => 'Appels sortants FACTEURS',
            'Version' => 1,
            'ControllerDirectory' => 'UNA_Fact',
            'ControllerStart' => 'index',
            'Activities' => ['1eda085380844a56b3efe3f594d8e900', '7380d7e0a2454340b4a9dc380740c3c4'],
        ],
        ['Name' => 'GREENPEACE UPGRADE',
            'Commentaire' => 'Appels entrants',
            'Version' => 2,
            'ControllerDirectory' => 'GP_Upgrade',
            'ControllerStart' => 'search',
            'Activities' => ['88dadd136eab42f385bc3a8c314991d7'],
            'AutoSearch' => ['TEL1', 'TEL2'],
            'SearchFilter' => [],
            'IncomingQualificationError' => '3f236b09dfaa4de1bb6f3ed3293b34e3',
        ],
        ['Name' => 'GREENPEACE LEADS CARITATIFS',
            'Commentaire' => '',
            'Version' => 1,
            'ControllerDirectory' => 'GP_Leads',
            'ControllerStart' => 'index',
            'Activities' => ['d1340400746448499870ebd8ac46faff'],
        ],
    ],
];

